-- ============================================================================
-- ADD USERS WITH SPECIFIC DETAILS
-- ============================================================================
-- This script creates users with provided emails and townships

-- No phone function needed, setting phone to NULL

-- Step 2: Insert users
WITH numbered_names AS (
    SELECT
        first_name,
        last_name,
        email,
        township
    FROM (
    VALUES
    ('Anele', 'Mthembu', 'anele.mthembu@gmail.com', 'Dobsonville'),
    ('Ayanda', 'Ngcobo', 'ayanda.ngcobo@gmail.com', 'Dobsonville Ext 1'),
    ('Babalwa', 'Mkhize', 'babalwa.mkhize@gmail.com', 'Dobsonville Ext 2'),
    ('Bongani', 'Zuma', 'bongani.zuma@gmail.com', 'Dobsonville'),
    ('Busisiwe', 'Dlamini', 'busisiwe.dlamini@gmail.com', 'Dobsonville Ext 1'),
    ('Fezile', 'Mabaso', 'fezile.mabaso@gmail.com', 'Dobsonville Ext 2'),
    ('Gugulethu', 'Mkhwanazi', 'gugulethu.mkhwanazi@gmail.com', 'Dobsonville'),
    ('Khanyisile', 'Majozi', 'khanyisile.majozi@gmail.com', 'Dobsonville Ext 1'),
    ('Lindokuhle', 'Mthembu', 'lindokuhle.mthembu@gmail.com', 'Dobsonville Ext 2'),
    ('Lungile', 'Ntuli', 'lungile.ntuli@gmail.com', 'Dobsonville'),
    ('Luyanda', 'Mhlongo', 'luyanda.mhlongo@gmail.com', 'Dobsonville Ext 1'),
    ('Mandla', 'Khumalo', 'mandla.khumalo@gmail.com', 'Dobsonville Ext 2'),
    ('Mbali', 'Mthethwa', 'mbali.mthethwa@gmail.com', 'Dobsonville'),
    ('Melusi', 'Mabena', 'melusi.mabena@gmail.com', 'Dobsonville Ext 1'),
    ('Menzi', 'Ngwenya', 'menzi.ngwenya@gmail.com', 'Dobsonville Ext 2'),
    ('Minenhle', 'Zungu', 'minenhle.zungu@gmail.com', 'Dobsonville'),
    ('Nandi', 'Mkhize', 'nandi.mkhize@gmail.com', 'Dobsonville Ext 1'),
    ('Nhlanhla', 'Mabaso', 'nhlanhla.mabaso@gmail.com', 'Dobsonville Ext 2'),
    ('Nokuthula', 'Dlamini', 'nokuthula.dlamini@gmail.com', 'Dobsonville'),
    ('Nomvula', 'Majozi', 'nomvula.majozi@gmail.com', 'Dobsonville Ext 1'),
    ('Nosipho', 'Mthembu', 'nosipho.mthembu@gmail.com', 'Dobsonville Ext 2'),
    ('Ntokozo', 'Ngcobo', 'ntokozo.ngcobo@gmail.com', 'Dobsonville'),
    ('Ntsikelelo', 'Mhlongo', 'ntsikelelo.mhlongo@gmail.com', 'Dobsonville Ext 1'),
    ('Nwabisa', 'Ntuli', 'nwabisa.ntuli@gmail.com', 'Dobsonville Ext 2'),
    ('Phindile', 'Zuma', 'phindile.zuma@gmail.com', 'Dobsonville'),
    ('Sanele', 'Mkhwanazi', 'sanele.mkhwanazi@gmail.com', 'Dobsonville Ext 1'),
    ('Sbusiso', 'Khumalo', 'sbusiso.khumalo@gmail.com', 'Dobsonville Ext 2'),
    ('Sibongile', 'Mthethwa', 'sibongile.mthethwa@gmail.com', 'Dobsonville'),
    ('Simphiwe', 'Ngwenya', 'simphiwe.ngwenya@gmail.com', 'Dobsonville Ext 1'),
    ('Siphesihle', 'Zungu', 'siphesihle.zungu@gmail.com', 'Dobsonville Ext 2'),
    ('Siyabonga', 'Mkhize', 'siyabonga.mkhize@gmail.com', 'Dobsonville'),
    ('Sizwe', 'Mabena', 'sizwe.mabena@gmail.com', 'Dobsonville Ext 1'),
    ('Thandeka', 'Dlamini', 'thandeka.dlamini@gmail.com', 'Dobsonville Ext 2'),
    ('Thando', 'Majozi', 'thando.majozi@gmail.com', 'Dobsonville'),
    ('Themba', 'Mthembu', 'themba.mthembu@gmail.com', 'Dobsonville Ext 1'),
    ('Thobeka', 'Ngcobo', 'thobeka.ngcobo@gmail.com', 'Dobsonville Ext 2'),
    ('Thulani', 'Mhlongo', 'thulani.mhlongo@gmail.com', 'Dobsonville'),
    ('Vuyani', 'Ntuli', 'vuyani.ntuli@gmail.com', 'Dobsonville Ext 1'),
    ('Vuyelwa', 'Zuma', 'vuyelwa.zuma@gmail.com', 'Dobsonville Ext 2'),
    ('Xolani', 'Mkhwanazi', 'xolani.mkhwanazi@gmail.com', 'Dobsonville'),
    ('Yandiswa', 'Khumalo', 'yandiswa.khumalo@gmail.com', 'Dobsonville Ext 1'),
    ('Yoliswa', 'Mthethwa', 'yoliswa.mthethwa@gmail.com', 'Dobsonville Ext 2'),
    ('Zanele', 'Ngwenya', 'zanele.ngwenya@gmail.com', 'Dobsonville'),
    ('Zandile', 'Zungu', 'zandile.zungu@gmail.com', 'Dobsonville Ext 1'),
    ('Zinhle', 'Mkhize', 'zinhle.mkhize@gmail.com', 'Dobsonville Ext 2'),
    ('Zola', 'Mabena', 'zola.mabena@gmail.com', 'Dobsonville'),
    ('Zwelakhe', 'Dlamini', 'zwelakhe.dlamini@gmail.com', 'Dobsonville Ext 1'),
    ('Zwelihle', 'Majozi', 'zwelihle.majozi@gmail.com', 'Dobsonville Ext 2'),
    ('Zodwa', 'Mthembu', 'zodwa.mthembu@gmail.com', 'Dobsonville'),
    ('Zukiswa', 'Ngcobo', 'zukiswa.ngcobo@gmail.com', 'Dobsonville Ext 1'),
    ('Hlengiwe', 'Moloi', 'hlengiwe.moloi@gmail.com', 'Dobsonville Ext 2'),
    ('Andile', 'Dlamini', 'andile.dlamini@gmail.com', 'Dobsonville'),
    ('Anele', 'Khumalo', 'anele.khumalo@gmail.com', 'Dobsonville Ext 1'),
    ('Ayabonga', 'Zulu', 'ayabonga.zulu@gmail.com', 'Dobsonville Ext 2'),
    ('Bhekisisa', 'Ngcobo', 'bhekisisa.ngcobo@gmail.com', 'Dobsonville'),
    ('Bongiwe', 'Mthembu', 'bongiwe.mthembu@gmail.com', 'Dobsonville Ext 1'),
    ('Buhle', 'Mkhize', 'buhle.mkhize@gmail.com', 'Dobsonville Ext 2'),
    ('Dumisani', 'Mabaso', 'dumisani.mabaso@gmail.com', 'Dobsonville'),
    ('Fikile', 'Ntuli', 'fikile.ntuli@gmail.com', 'Dobsonville Ext 1'),
    ('Gugu', 'Mhlongo', 'gugu.mhlongo@gmail.com', 'Dobsonville Ext 2'),
    ('Hlengiwe', 'Zungu', 'hlengiwe.zungu@gmail.com', 'Dobsonville'),
    ('Jabulani', 'Majozi', 'jabulani.majozi@gmail.com', 'Dobsonville Ext 1'),
    ('Kagiso', 'Ngwenya', 'kagiso.ngwenya@gmail.com', 'Dobsonville Ext 2'),
    ('Khaya', 'Mthethwa', 'khaya.mthethwa@gmail.com', 'Dobsonville'),
    ('Khanyisa', 'Dlamini', 'khanyisa.dlamini@gmail.com', 'Dobsonville Ext 1'),
    ('Lindiwe', 'Mabena', 'lindiwe.mabena@gmail.com', 'Dobsonville Ext 2'),
    ('Lulama', 'Khumalo', 'lulama.khumalo@gmail.com', 'Dobsonville'),
    ('Lungile', 'Zulu', 'lungile.zulu@gmail.com', 'Dobsonville Ext 1'),
    ('Luyolo', 'Ngcobo', 'luyolo.ngcobo@gmail.com', 'Dobsonville Ext 2'),
    ('Mangaliso', 'Mthembu', 'mangaliso.mthembu@gmail.com', 'Dobsonville'),
    ('Mbalenhle', 'Mkhize', 'mbalenhle.mkhize@gmail.com', 'Dobsonville Ext 1'),
    ('Mduduzi', 'Mabaso', 'mduduzi.mabaso@gmail.com', 'Dobsonville Ext 2'),
    ('Melokuhle', 'Ntuli', 'melokuhle.ntuli@gmail.com', 'Dobsonville'),
    ('Menzi', 'Mhlongo', 'menzi.mhlongo@gmail.com', 'Dobsonville Ext 1'),
    ('Minenhle', 'Zungu', 'minenhle.zungu2@gmail.com', 'Dobsonville Ext 2'),
    ('Mpho', 'Majozi', 'mpho.majozi@gmail.com', 'Dobsonville'),
    ('Nandipha', 'Ngwenya', 'nandipha.ngwenya@gmail.com', 'Dobsonville Ext 1'),
    ('Nhlakanipho', 'Mthethwa', 'nhlakanipho.mthethwa@gmail.com', 'Dobsonville Ext 2'),
    ('Nkosinathi', 'Dlamini', 'nkosinathi.dlamini@gmail.com', 'Dobsonville'),
    ('Nokubonga', 'Mabena', 'nokubonga.mabena@gmail.com', 'Dobsonville Ext 1'),
    ('Nomathamsanqa', 'Khumalo', 'nomathamsanqa.khumalo@gmail.com', 'Dobsonville Ext 2'),
    ('Nomonde', 'Zulu', 'nomonde.zulu@gmail.com', 'Dobsonville'),
    ('Nompumelelo', 'Ngcobo', 'nompumelelo.ngcobo@gmail.com', 'Dobsonville Ext 1'),
    ('Nontobeko', 'Zulu', 'nontobeko.zulu@gmail.com', 'Dobsonville'),
    ('Noxolo', 'Ngcobo', 'noxolo.ngcobo@gmail.com', 'Dobsonville Ext 1'),
    ('Ntombifuthi', 'Mthembu', 'ntombifuthi.mthembu@gmail.com', 'Dobsonville Ext 2'),
    ('Ntsikelelo', 'Mkhize', 'ntsikelelo.mkhize@gmail.com', 'Dobsonville'),
    ('Nwabisa', 'Mabaso', 'nwabisa.mabaso@gmail.com', 'Dobsonville Ext 1'),
    ('Phakamani', 'Ntuli', 'phakamani.ntuli@gmail.com', 'Dobsonville Ext 2'),
    ('Phindile', 'Mhlongo', 'phindile.mhlongo@gmail.com', 'Dobsonville'),
    ('Sanele', 'Zungu', 'sanele.zungu@gmail.com', 'Dobsonville Ext 1'),
    ('Sbusisiwe', 'Majozi', 'sbusisiwe.majozi@gmail.com', 'Dobsonville Ext 2'),
    ('Sibongile', 'Ngwenya', 'sibongile.ngwenya@gmail.com', 'Dobsonville'),
    ('Simphiwe', 'Mthethwa', 'simphiwe.mthethwa@gmail.com', 'Dobsonville Ext 1'),
    ('Siphesihle', 'Dlamini', 'siphesihle.dlamini@gmail.com', 'Dobsonville Ext 2'),
    ('Siyanda', 'Mabena', 'siyanda.mabena@gmail.com', 'Dobsonville'),
    ('Siyavuya', 'Khumalo', 'siyavuya.khumalo@gmail.com', 'Dobsonville Ext 1'),
    ('Sizwe', 'Zulu', 'sizwe.zulu@gmail.com', 'Dobsonville Ext 2'),
    ('Thabang', 'Ngcobo', 'thabang.ngcobo@gmail.com', 'Dobsonville'),
    ('Thandeka', 'Mthembu', 'thandeka.mthembu@gmail.com', 'Dobsonville Ext 1'),
    ('Thando', 'Mkhize', 'thando.mkhize@gmail.com', 'Dobsonville Ext 2'),
    ('Themba', 'Mabaso', 'themba.mabaso@gmail.com', 'Dobsonville'),
    ('Thobeka', 'Ntuli', 'thobeka.ntuli@gmail.com', 'Dobsonville Ext 1'),
    ('Thulani', 'Mhlongo', 'thulani.mhlongo2@gmail.com', 'Dobsonville Ext 2'),
    ('Vuyani', 'Zungu', 'vuyani.zungu@gmail.com', 'Dobsonville'),
    ('Vuyelwa', 'Majozi', 'vuyelwa.majozi@gmail.com', 'Dobsonville Ext 1'),
    ('Xolani', 'Ngwenya', 'xolani.ngwenya@gmail.com', 'Dobsonville Ext 2'),
    ('Yandiswa', 'Mthethwa', 'yandiswa.mthethwa@gmail.com', 'Dobsonville'),
    ('Yonela', 'Dlamini', 'yonela.dlamini@gmail.com', 'Dobsonville Ext 1'),
    ('Zanele', 'Mabena', 'zanele.mabena@gmail.com', 'Dobsonville Ext 2'),
    ('Zandile', 'Khumalo', 'zandile.khumalo@gmail.com', 'Dobsonville'),
    ('Zikhona', 'Zulu', 'zikhona.zulu@gmail.com', 'Dobsonville Ext 1'),
    ('Zimasa', 'Ngcobo', 'zimasa.ngcobo@gmail.com', 'Dobsonville Ext 2'),
    ('Zinhle', 'Mthembu', 'zinhle.mthembu2@gmail.com', 'Dobsonville'),
    ('Zola', 'Mkhize', 'zola.mkhize@gmail.com', 'Dobsonville Ext 1'),
    ('Zukiswa', 'Mabaso', 'zukiswa.mabaso@gmail.com', 'Dobsonville Ext 2'),
    ('Akhona', 'Ntuli', 'akhona.ntuli@gmail.com', 'Dobsonville'),
    ('Andiswa', 'Mhlongo', 'andiswa.mhlongo@gmail.com', 'Dobsonville Ext 1'),
    ('Anele', 'Zungu', 'anele.zungu@gmail.com', 'Dobsonville Ext 2'),
    ('Asanda', 'Majozi', 'asanda.majozi@gmail.com', 'Dobsonville'),
    ('Ayanda', 'Ngwenya', 'ayanda.ngwenya@gmail.com', 'Dobsonville Ext 1'),
    ('Babalwa', 'Mthethwa', 'babalwa.mthethwa@gmail.com', 'Dobsonville Ext 2'),
    ('Bandile', 'Dlamini', 'bandile.dlamini@gmail.com', 'Dobsonville'),
    ('Bhekisisa', 'Mabena', 'bhekisisa.mabena@gmail.com', 'Dobsonville Ext 1'),
    ('Bongani', 'Khumalo', 'bongani.khumalo@gmail.com', 'Dobsonville Ext 2'),
    ('Buhle', 'Zulu', 'buhle.zulu@gmail.com', 'Dobsonville'),
    ('Busisiwe', 'Ngcobo', 'busisiwe.ngcobo@gmail.com', 'Dobsonville Ext 1'),
    ('Dineo', 'Mthembu', 'dineo.mthembu@gmail.com', 'Dobsonville Ext 2'),
    ('Dumisani', 'Mkhize', 'dumisani.mkhize@gmail.com', 'Dobsonville'),
    ('Fikile', 'Mabaso', 'fikile.mabaso2@gmail.com', 'Dobsonville Ext 1'),
    ('Gugu', 'Ntuli', 'gugu.ntuli@gmail.com', 'Dobsonville Ext 2'),
    ('Hlengiwe', 'Mhlongo', 'hlengiwe.mhlongo@gmail.com', 'Dobsonville'),
    ('Jabulani', 'Zungu', 'jabulani.zungu@gmail.com', 'Dobsonville Ext 1'),
    ('Kagiso', 'Majozi', 'kagiso.majozi@gmail.com', 'Dobsonville'),
    ('Khaya', 'Ngwenya', 'khaya.ngwenya@gmail.com', 'Dobsonville Ext 1'),
    ('Khanyisa', 'Mthethwa', 'khanyisa.mthethwa@gmail.com', 'Dobsonville Ext 2'),
    ('Lindiwe', 'Dlamini', 'lindiwe.dlamini@gmail.com', 'Dobsonville'),
    ('Lulama', 'Mabena', 'lulama.mabena@gmail.com', 'Dobsonville Ext 1'),
    ('Lungile', 'Khumalo', 'lungile.khumalo@gmail.com', 'Dobsonville Ext 2'),
    ('Luyolo', 'Zulu', 'luyolo.zulu@gmail.com', 'Dobsonville'),
    ('Mangaliso', 'Ngcobo', 'mangaliso.ngcobo@gmail.com', 'Dobsonville Ext 1'),
    ('Mbalenhle', 'Mthembu', 'mbalenhle.mthembu@gmail.com', 'Dobsonville Ext 2'),
    ('Mduduzi', 'Mkhize', 'mduduzi.mkhize@gmail.com', 'Dobsonville'),
    ('Melokuhle', 'Mabaso', 'melokuhle.mabaso@gmail.com', 'Dobsonville Ext 1'),
    ('Menzi', 'Ntuli', 'menzi.ntuli@gmail.com', 'Dobsonville Ext 2'),
    ('Minenhle', 'Mhlongo', 'minenhle.mhlongo@gmail.com', 'Dobsonville'),
    ('Mpho', 'Zungu', 'mpho.zungu@gmail.com', 'Dobsonville Ext 1'),
    ('Nandipha', 'Majozi', 'nandipha.majozi@gmail.com', 'Dobsonville Ext 2'),
    ('Nhlakanipho', 'Ngwenya', 'nhlakanipho.ngwenya@gmail.com', 'Dobsonville'),
    ('Nkosinathi', 'Mthethwa', 'nkosinathi.mthethwa@gmail.com', 'Dobsonville Ext 1'),
    ('Nokubonga', 'Dlamini', 'nokubonga.dlamini@gmail.com', 'Dobsonville Ext 2'),
    ('Nomathamsanqa', 'Mabena', 'nomathamsanqa.mabena@gmail.com', 'Dobsonville'),
    ('Nomonde', 'Khumalo', 'nomonde.khumalo@gmail.com', 'Dobsonville Ext 1'),
    ('Nompumelelo', 'Zulu', 'nompumelelo.zulu@gmail.com', 'Dobsonville Ext 2'),
    ('Nontobeko', 'Ngcobo', 'nontobeko.ngcobo@gmail.com', 'Dobsonville'),
    ('Noxolo', 'Mthembu', 'noxolo.mthembu@gmail.com', 'Dobsonville Ext 1'),
    ('Ntombifuthi', 'Mkhize', 'ntombifuthi.mkhize@gmail.com', 'Dobsonville Ext 2'),
    ('Ntsikelelo', 'Mabaso', 'ntsikelelo.mabaso@gmail.com', 'Dobsonville'),
    ('Nwabisa', 'Ntuli', 'nwabisa.ntuli@gmail.com', 'Dobsonville Ext 1'),
    ('Phakamani', 'Mhlongo', 'phakamani.mhlongo@gmail.com', 'Dobsonville Ext 2'),
    ('Phindile', 'Zungu', 'phindile.zungu@gmail.com', 'Dobsonville'),
    ('Sanele', 'Majozi', 'sanele.majozi@gmail.com', 'Dobsonville Ext 1'),
    ('Sbusisiwe', 'Ngwenya', 'sbusisiwe.ngwenya@gmail.com', 'Dobsonville Ext 2'),
    ('Sibongile', 'Mthethwa', 'sibongile.mthethwa2@gmail.com', 'Dobsonville'),
    ('Simphiwe', 'Dlamini', 'simphiwe.dlamini@gmail.com', 'Dobsonville Ext 1'),
    ('Siphesihle', 'Mabena', 'siphesihle.mabena@gmail.com', 'Dobsonville Ext 2'),
    ('Siyanda', 'Khumalo', 'siyanda.khumalo@gmail.com', 'Dobsonville'),
    ('Siyavuya', 'Zulu', 'siyavuya.zulu@gmail.com', 'Dobsonville Ext 1'),
    ('Sizwe', 'Ngcobo', 'sizwe.ngcobo@gmail.com', 'Dobsonville Ext 2'),
    ('Thabang', 'Mthembu', 'thabang.mthembu@gmail.com', 'Dobsonville'),
    ('Thandeka', 'Mkhize', 'thandeka.mkhize2@gmail.com', 'Dobsonville Ext 1'),
    ('Thando', 'Mabaso', 'thando.mabaso@gmail.com', 'Dobsonville Ext 2'),
    ('Themba', 'Ntuli', 'themba.ntuli@gmail.com', 'Dobsonville'),
    ('Thobeka', 'Mhlongo', 'thobeka.mhlongo@gmail.com', 'Dobsonville Ext 1'),
    ('Thulani', 'Zungu', 'thulani.zungu@gmail.com', 'Dobsonville Ext 2'),
    ('Vuyani', 'Majozi', 'vuyani.majozi@gmail.com', 'Dobsonville'),
    ('Vuyelwa', 'Ngwenya', 'vuyelwa.ngwenya@gmail.com', 'Dobsonville Ext 1'),
    ('Xolani', 'Mthethwa', 'xolani.mthethwa@gmail.com', 'Dobsonville Ext 2'),
    ('Yandiswa', 'Dlamini', 'yandiswa.dlamini@gmail.com', 'Dobsonville'),
    ('Yonela', 'Mabena', 'yonela.mabena@gmail.com', 'Dobsonville Ext 1'),
    ('Zanele', 'Khumalo', 'zanele.khumalo@gmail.com', 'Dobsonville Ext 2'),
    ('Zandile', 'Zulu', 'zandile.zulu3@gmail.com', 'Dobsonville'),
    ('Zikhona', 'Ngcobo', 'zikhona.ngcobo2@gmail.com', 'Dobsonville Ext 1'),
    ('Zimasa', 'Mthembu', 'zimasa.mthembu@gmail.com', 'Dobsonville'),
    ('Zinhle', 'Mkhize', 'zinhle.mkhize2@gmail.com', 'Dobsonville Ext 1'),
    ('Zola', 'Mabaso', 'zola.mabaso@gmail.com', 'Dobsonville Ext 2'),
    ('Zukiswa', 'Ntuli', 'zukiswa.ntuli@gmail.com', 'Dobsonville'),
    ('Akhona', 'Mhlongo', 'akhona.mhlongo@gmail.com', 'Dobsonville Ext 1'),
    ('Andiswa', 'Zungu', 'andiswa.zungu@gmail.com', 'Dobsonville Ext 2'),
    ('Anele', 'Majozi', 'anele.majozi@gmail.com', 'Dobsonville'),
    ('Asanda', 'Ngwenya', 'asanda.ngwenya@gmail.com', 'Dobsonville Ext 1'),
    ('Ayanda', 'Mthethwa', 'ayanda.mthethwa@gmail.com', 'Dobsonville Ext 2'),
    ('Babalwa', 'Dlamini', 'babalwa.dlamini@gmail.com', 'Dobsonville'),
    ('Bandile', 'Mabena', 'bandile.mabena@gmail.com', 'Dobsonville Ext 1'),
    ('Bhekisisa', 'Khumalo', 'bhekisisa.khumalo@gmail.com', 'Dobsonville Ext 2'),
    ('Bongiwe', 'Zulu', 'bongiwe.zulu@gmail.com', 'Dobsonville'),
    ('Buhle', 'Ngcobo', 'buhle.ngcobo@gmail.com', 'Dobsonville Ext 1'),
    ('Busisiwe', 'Mthembu', 'busisiwe.mthembu2@gmail.com', 'Dobsonville Ext 2'),
    ('Dineo', 'Mkhize', 'dineo.mkhize@gmail.com', 'Dobsonville'),
    ('Dumisani', 'Mabaso', 'dumisani.mabaso2@gmail.com', 'Dobsonville Ext 1'),
    ('Fikile', 'Ntuli', 'fikile.ntuli2@gmail.com', 'Dobsonville Ext 2'),
    ('Gugu', 'Mhlongo', 'gugu.mhlongo2@gmail.com', 'Dobsonville'),
    ('Hlengiwe', 'Zungu', 'hlengiwe.zungu2@gmail.com', 'Dobsonville Ext 1'),
    ('Jabulani', 'Majozi', 'jabulani.majozi2@gmail.com', 'Dobsonville Ext 2'),
    ('Kagiso', 'Ngwenya', 'kagiso.ngwenya2@gmail.com', 'Dobsonville'),
    ('Khaya', 'Mthethwa', 'khaya.mthethwa2@gmail.com', 'Dobsonville Ext 1'),
    ('Khanyisa', 'Dlamini', 'khanyisa.dlamini2@gmail.com', 'Dobsonville Ext 2'),
    ('Lindiwe', 'Mabena', 'lindiwe.mabena2@gmail.com', 'Dobsonville'),
    ('Lulama', 'Khumalo', 'lulama.khumalo2@gmail.com', 'Dobsonville Ext 1'),
    ('Lungile', 'Zulu', 'lungile.zulu2@gmail.com', 'Dobsonville Ext 2'),
    ('Luyolo', 'Ngcobo', 'luyolo.ngcobo2@gmail.com', 'Dobsonville'),
    ('Mangaliso', 'Mthembu', 'mangaliso.mthembu2@gmail.com', 'Dobsonville Ext 1'),
    ('Mbalenhle', 'Mkhize', 'mbalenhle.mkhize2@gmail.com', 'Dobsonville Ext 2'),
    ('Mduduzi', 'Mabaso', 'mduduzi.mabaso2@gmail.com', 'Dobsonville'),
    ('Melokuhle', 'Ntuli', 'melokuhle.ntuli2@gmail.com', 'Dobsonville Ext 1'),
    ('Menzi', 'Mhlongo', 'menzi.mhlongo2@gmail.com', 'Dobsonville Ext 2'),
    ('Minenhle', 'Zungu', 'minenhle.zungu3@gmail.com', 'Dobsonville'),
    ('Mpho', 'Majozi', 'mpho.majozi2@gmail.com', 'Dobsonville Ext 1'),
    ('Nandipha', 'Ngwenya', 'nandipha.ngwenya2@gmail.com', 'Dobsonville Ext 2'),
    ('Nhlakanipho', 'Mthethwa', 'nhlakanipho.mthethwa3@gmail.com', 'Dobsonville'),
    ('Nkosinathi', 'Dlamini', 'nkosinathi.dlamini2@gmail.com', 'Dobsonville Ext 1'),
    ('Nokubonga', 'Mabena', 'nokubonga.mabena2@gmail.com', 'Dobsonville Ext 2'),
    ('Nomathamsanqa', 'Khumalo', 'nomathamsanqa.khumalo2@gmail.com', 'Dobsonville'),
    ('Nomonde', 'Zulu', 'nomonde.zulu2@gmail.com', 'Dobsonville Ext 1'),
    ('Nompumelelo', 'Ngcobo', 'nompumelelo.ngcobo2@gmail.com', 'Dobsonville Ext 2'),
    ('Nonhlanhla', 'Mthembu', 'nonhlanhla.mthembu2@gmail.com', 'Dobsonville'),
    ('Nosihle', 'Mkhize', 'nosihle.mkhize2@gmail.com', 'Dobsonville Ext 1'),
    ('Ntando', 'Mabaso', 'ntando.mabaso2@gmail.com', 'Dobsonville Ext 2'),
    ('Ntombizodwa', 'Ntuli', 'ntombizodwa.ntuli2@gmail.com', 'Dobsonville'),
    ('Ntombezinhle', 'Mhlongo', 'ntombezinhle.mhlongo2@gmail.com', 'Dobsonville Ext 1'),
    ('Nwabisa', 'Zungu', 'nwabisa.zungu2@gmail.com', 'Dobsonville Ext 2'),
    ('Phakamani', 'Majozi', 'phakamani.majozi2@gmail.com', 'Dobsonville'),
    ('Phindile', 'Ngwenya', 'phindile.ngwenya2@gmail.com', 'Dobsonville Ext 1'),
    ('Sanele', 'Mthembu', 'sanele.mthembu2@gmail.com', 'Dobsonville'),
    ('Sbusiso', 'Mkhize', 'sbusiso.mkhize@gmail.com', 'Dobsonville Ext 1'),
    ('Sibongile', 'Mabaso', 'sibongile.mabaso@gmail.com', 'Dobsonville Ext 2'),
    ('Simphiwe', 'Ntuli', 'simphiwe.ntuli@gmail.com', 'Dobsonville'),
    ('Siphesihle', 'Mhlongo', 'siphesihle.mhlongo@gmail.com', 'Dobsonville Ext 1'),
    ('Siyanda', 'Zungu', 'siyanda.zungu@gmail.com', 'Dobsonville Ext 2'),
    ('Siyavuya', 'Majozi', 'siyavuya.majozi@gmail.com', 'Dobsonville'),
    ('Sizwe', 'Ngwenya', 'sizwe.ngwenya@gmail.com', 'Dobsonville Ext 1'),
    ('Thabang', 'Mthethwa', 'thabang.mthethwa2@gmail.com', 'Dobsonville Ext 2'),
    ('Thandeka', 'Dlamini', 'thandeka.dlamini2@gmail.com', 'Dobsonville'),
    ('Thando', 'Mabena', 'thando.mabena@gmail.com', 'Dobsonville Ext 1'),
    ('Themba', 'Khumalo', 'themba.khumalo2@gmail.com', 'Dobsonville Ext 2'),
    ('Thobeka', 'Zulu', 'thobeka.zulu2@gmail.com', 'Dobsonville'),
    ('Thulani', 'Ngcobo', 'thulani.ngcobo2@gmail.com', 'Dobsonville Ext 1'),
    ('Vuyani', 'Mthembu', 'vuyani.mthembu2@gmail.com', 'Dobsonville Ext 2'),
    ('Vuyelwa', 'Mkhize', 'vuyelwa.mkhize@gmail.com', 'Dobsonville'),
    ('Xolani', 'Mabaso', 'xolani.mabaso@gmail.com', 'Dobsonville Ext 1'),
    ('Yandiswa', 'Ntuli', 'yandiswa.ntuli@gmail.com', 'Dobsonville Ext 2'),
    ('Yonela', 'Mhlongo', 'yonela.mhlongo@gmail.com', 'Dobsonville'),
    ('Zanele', 'Zungu', 'zanele.zungu4@gmail.com', 'Dobsonville Ext 1'),
    ('Zandile', 'Majozi', 'zandile.majozi@gmail.com', 'Dobsonville Ext 2'),
    ('Zikhona', 'Ngwenya', 'zikhona.ngwenya@gmail.com', 'Dobsonville'),
    ('Zimasa', 'Mthethwa', 'zimasa.mthethwa2@gmail.com', 'Dobsonville Ext 1'),
    ('Zinhle', 'Dlamini', 'zinhle.dlamini@gmail.com', 'Dobsonville Ext 2'),
    ('Zola', 'Mabena', 'zola.mabena2@gmail.com', 'Dobsonville'),
    ('Zukiswa', 'Khumalo', 'zukiswa.khumalo@gmail.com', 'Dobsonville Ext 1'),
    ('Akhona', 'Zulu', 'akhona.zulu@gmail.com', 'Dobsonville Ext 2'),
    ('Andiswa', 'Ngcobo', 'andiswa.ngcobo@gmail.com', 'Dobsonville'),
    ('Anele', 'Mthembu', 'anele.mthembu2@gmail.com', 'Dobsonville Ext 1'),
    ('Asanda', 'Mkhize', 'asanda.mkhize@gmail.com', 'Dobsonville Ext 2'),
    ('Ayanda', 'Mabaso', 'ayanda.mabaso@gmail.com', 'Dobsonville'),
    ('Babalwa', 'Ntuli', 'babalwa.ntuli@gmail.com', 'Dobsonville Ext 1'),
    ('Bandile', 'Mhlongo', 'bandile.mhlongo@gmail.com', 'Dobsonville Ext 2'),
    ('Bhekisisa', 'Zungu', 'bhekisisa.zungu@gmail.com', 'Dobsonville'),
    ('Bongiwe', 'Majozi', 'bongiwe.majozi@gmail.com', 'Dobsonville Ext 1'),
    ('Buhle', 'Ngwenya', 'buhle.ngwenya@gmail.com', 'Dobsonville Ext 2'),
    ('Busisiwe', 'Mthethwa', 'busisiwe.mthethwa3@gmail.com', 'Dobsonville'),
    ('Dineo', 'Dlamini', 'dineo.dlamini2@gmail.com', 'Dobsonville Ext 1'),
    ('Dumisani', 'Mabena', 'dumisani.mabena3@gmail.com', 'Dobsonville Ext 2'),
    ('Fikile', 'Khumalo', 'fikile.khumalo@gmail.com', 'Dobsonville'),
    ('Gugu', 'Zulu', 'gugu.zulu@gmail.com', 'Dobsonville Ext 1'),
    ('Hlengiwe', 'Ngcobo', 'hlengiwe.ngcobo@gmail.com', 'Dobsonville Ext 2'),
    ('Jabulani', 'Mthembu', 'jabulani.mthembu@gmail.com', 'Dobsonville'),
    ('Kagiso', 'Mkhize', 'kagiso.mkhize@gmail.com', 'Dobsonville Ext 1'),
    ('Khaya', 'Mabaso', 'khaya.mabaso@gmail.com', 'Dobsonville Ext 2'),
    ('Khanyisa', 'Ntuli', 'khanyisa.ntuli@gmail.com', 'Dobsonville'),
    ('Lindiwe', 'Mhlongo', 'lindiwe.mhlongo@gmail.com', 'Dobsonville Ext 1'),
    ('Lulama', 'Zungu', 'lulama.zungu@gmail.com', 'Dobsonville Ext 2'),
    ('Lungile', 'Majozi', 'lungile.majozi@gmail.com', 'Dobsonville'),
    ('Luyolo', 'Ngwenya', 'luyolo.ngwenya3@gmail.com', 'Dobsonville Ext 1'),
    ('Mangaliso', 'Mkhize', 'mangaliso.mkhize@gmail.com', 'Dobsonville'),
    ('Mbalenhle', 'Mabaso', 'mbalenhle.mabaso@gmail.com', 'Dobsonville Ext 1'),
    ('Mduduzi', 'Ntuli', 'mduduzi.ntuli@gmail.com', 'Dobsonville Ext 2'),
    ('Melokuhle', 'Mhlongo', 'melokuhle.mhlongo@gmail.com', 'Dobsonville'),
    ('Menzi', 'Zungu', 'menzi.zungu@gmail.com', 'Dobsonville Ext 1'),
    ('Minenhle', 'Majozi', 'minenhle.majozi@gmail.com', 'Dobsonville Ext 2'),
    ('Mpho', 'Ngwenya', 'mpho.ngwenya@gmail.com', 'Dobsonville'),
    ('Nandipha', 'Mthethwa', 'nandipha.mthethwa@gmail.com', 'Dobsonville Ext 1'),
    ('Nhlakanipho', 'Dlamini', 'nhlakanipho.dlamini@gmail.com', 'Dobsonville Ext 2'),
    ('Nkosinathi', 'Mabena', 'nkosinathi.mabena@gmail.com', 'Dobsonville'),
    ('Nokubonga', 'Khumalo', 'nokubonga.khumalo@gmail.com', 'Dobsonville Ext 1'),
    ('Nomathamsanqa', 'Zulu', 'nomathamsanqa.zulu@gmail.com', 'Dobsonville Ext 2'),
    ('Nomonde', 'Ngcobo', 'nomonde.ngcobo@gmail.com', 'Dobsonville'),
    ('Nompumelelo', 'Mthembu', 'nompumelelo.mthembu@gmail.com', 'Dobsonville Ext 1'),
    ('Nonhlanhla', 'Mkhize', 'nonhlanhla.mkhize@gmail.com', 'Dobsonville Ext 2'),
    ('Nosihle', 'Mabaso', 'nosihle.mabaso@gmail.com', 'Dobsonville'),
    ('Ntando', 'Ntuli', 'ntando.ntuli@gmail.com', 'Dobsonville Ext 1'),
    ('Ntombizodwa', 'Mhlongo', 'ntombizodwa.mhlongo@gmail.com', 'Dobsonville Ext 2'),
    ('Ntombezinhle', 'Zungu', 'ntombezinhle.zungu@gmail.com', 'Dobsonville'),
    ('Nwabisa', 'Majozi', 'nwabisa.majozi@gmail.com', 'Dobsonville Ext 1'),
    ('Phakamani', 'Ngwenya', 'phakamani.ngwenya@gmail.com', 'Dobsonville Ext 2'),
    ('Phindile', 'Mthethwa', 'phindile.mthethwa2@gmail.com', 'Dobsonville'),
    ('Sanele', 'Dlamini', 'sanele.dlamini@gmail.com', 'Dobsonville Ext 1'),
    ('Sbusiso', 'Mabena', 'sbusiso.mabena@gmail.com', 'Dobsonville Ext 2'),
    ('Sibongile', 'Khumalo', 'sibongile.khumalo@gmail.com', 'Dobsonville'),
    ('Simphiwe', 'Zulu', 'simphiwe.zulu2@gmail.com', 'Dobsonville Ext 1'),
    ('Siphesihle', 'Ngcobo', 'siphesihle.ngcobo@gmail.com', 'Dobsonville Ext 2'),
    ('Siyanda', 'Mthembu', 'siyanda.mthembu2@gmail.com', 'Dobsonville'),
    ('Siyavuya', 'Mkhize', 'siyavuya.mkhize2@gmail.com', 'Dobsonville Ext 1'),
    ('Sizwe', 'Mabaso', 'sizwe.mabaso2@gmail.com', 'Dobsonville Ext 2'),
    ('Thabang', 'Ntuli', 'thabang.ntuli@gmail.com', 'Dobsonville'),
    ('Thandeka', 'Mhlongo', 'thandeka.mhlongo2@gmail.com', 'Dobsonville Ext 1'),
    ('Thando', 'Zungu', 'thando.zungu@gmail.com', 'Dobsonville Ext 2'),
    ('Themba', 'Majozi', 'themba.majozi2@gmail.com', 'Dobsonville'),
    ('Thobeka', 'Ngwenya', 'thobeka.ngwenya@gmail.com', 'Dobsonville Ext 1'),
    ('Thulani', 'Mthethwa', 'thulani.mthethwa3@gmail.com', 'Dobsonville Ext 2'),
    ('Vuyani', 'Dlamini', 'vuyani.dlamini@gmail.com', 'Dobsonville'),
    ('Vuyelwa', 'Mabena', 'vuyelwa.mabena@gmail.com', 'Dobsonville Ext 1'),
    ('Xolani', 'Khumalo', 'xolani.khumalo@gmail.com', 'Dobsonville Ext 2'),
    ('Yandiswa', 'Zulu', 'yandiswa.zulu2@gmail.com', 'Dobsonville'),
    ('Yonela', 'Ngcobo', 'yonela.ngcobo@gmail.com', 'Dobsonville Ext 1'),
    ('Zanele', 'Mthembu', 'zanele.mthembu3@gmail.com', 'Dobsonville Ext 2'),
    ('Zandile', 'Mkhize', 'zandile.mkhize2@gmail.com', 'Dobsonville'),
    ('Zikhona', 'Mabaso', 'zikhona.mabaso@gmail.com', 'Dobsonville Ext 1'),
    ('Zimasa', 'Ntuli', 'zimasa.ntuli@gmail.com', 'Dobsonville Ext 2'),
    ('Zinhle', 'Mhlongo', 'zinhle.mhlongo2@gmail.com', 'Dobsonville'),
    ('Zola', 'Zungu', 'zola.zungu@gmail.com', 'Dobsonville Ext 1'),
    ('Zukiswa', 'Majozi', 'zukiswa.majozi2@gmail.com', 'Dobsonville Ext 2'),
    ('Akhona', 'Ngwenya', 'akhona.ngwenya@gmail.com', 'Dobsonville'),
    ('Andiswa', 'Mthethwa', 'andiswa.mthethwa2@gmail.com', 'Dobsonville Ext 1'),
    ('Phindile', 'Mkhize', 'phindile.mkhize@gmail.com', 'Dobsonville'),
    ('Sanele', 'Mabaso', 'sanele.mabaso@gmail.com', 'Dobsonville Ext 1'),
    ('Sbusiso', 'Ntuli', 'sbusiso.ntuli@gmail.com', 'Dobsonville Ext 2'),
    ('Sibongile', 'Mhlongo', 'sibongile.mhlongo2@gmail.com', 'Dobsonville'),
    ('Simphiwe', 'Zungu', 'simphiwe.zungu3@gmail.com', 'Dobsonville Ext 1'),
    ('Siphesihle', 'Majozi', 'siphesihle.majozi2@gmail.com', 'Dobsonville Ext 2'),
    ('Siyanda', 'Ngwenya', 'siyanda.ngwenya2@gmail.com', 'Dobsonville'),
    ('Siyavuya', 'Mthethwa', 'siyavuya.mthethwa3@gmail.com', 'Dobsonville Ext 1'),
    ('Sizwe', 'Dlamini', 'sizwe.dlamini@gmail.com', 'Dobsonville Ext 2'),
    ('Thabang', 'Mabena', 'thabang.mabena@gmail.com', 'Dobsonville'),
    ('Thandeka', 'Khumalo', 'thandeka.khumalo2@gmail.com', 'Dobsonville Ext 1'),
    ('Thando', 'Zulu', 'thando.zulu2@gmail.com', 'Dobsonville Ext 2'),
    ('Themba', 'Ngcobo', 'themba.ngcobo@gmail.com', 'Dobsonville'),
    ('Thobeka', 'Mthembu', 'thobeka.mthembu@gmail.com', 'Dobsonville Ext 1'),
    ('Thulani', 'Mkhize', 'thulani.mkhize3@gmail.com', 'Dobsonville Ext 2'),
    ('Vuyani', 'Mabaso', 'vuyani.mabaso@gmail.com', 'Dobsonville'),
    ('Vuyelwa', 'Ntuli', 'vuyelwa.ntuli@gmail.com', 'Dobsonville Ext 1'),
    ('Xolani', 'Mhlongo', 'xolani.mhlongo2@gmail.com', 'Dobsonville Ext 2'),
    ('Yandiswa', 'Zungu', 'yandiswa.zungu3@gmail.com', 'Dobsonville'),
    ('Yonela', 'Majozi', 'yonela.majozi@gmail.com', 'Dobsonville Ext 1'),
    ('Zanele', 'Ngwenya', 'zanele.ngwenya2@gmail.com', 'Dobsonville Ext 2'),
    ('Zandile', 'Mthethwa', 'zandile.mthethwa3@gmail.com', 'Dobsonville'),
    ('Zikhona', 'Dlamini', 'zikhona.dlamini@gmail.com', 'Dobsonville Ext 1'),
    ('Zimasa', 'Mabena', 'zimasa.mabena@gmail.com', 'Dobsonville Ext 2'),
    ('Zinhle', 'Khumalo', 'zinhle.khumalo2@gmail.com', 'Dobsonville'),
    ('Zola', 'Zulu', 'zola.zulu2@gmail.com', 'Dobsonville Ext 1'),
    ('Zukiswa', 'Ngcobo', 'zukiswa.ngcobo2@gmail.com', 'Dobsonville Ext 2'),
    ('Akhona', 'Mthembu', 'akhona.mthembu2@gmail.com', 'Dobsonville'),
    ('Andiswa', 'Mkhize', 'andiswa.mkhize2@gmail.com', 'Dobsonville Ext 1'),
    ('Anele', 'Mabaso', 'anele.mabaso@gmail.com', 'Dobsonville Ext 2'),
    ('Asanda', 'Ntuli', 'asanda.ntuli@gmail.com', 'Dobsonville'),
    ('Ayanda', 'Mhlongo', 'ayanda.mhlongo@gmail.com', 'Dobsonville Ext 1'),
    ('Babalwa', 'Zungu', 'babalwa.zungu@gmail.com', 'Dobsonville Ext 2'),
    ('Bandile', 'Majozi', 'bandile.majozi@gmail.com', 'Dobsonville'),
    ('Bhekisisa', 'Ngwenya', 'bhekisisa.ngwenya2@gmail.com', 'Dobsonville Ext 1'),
    ('Bongiwe', 'Mthethwa', 'bongiwe.mthethwa2@gmail.com', 'Dobsonville Ext 2'),
    ('Buhle', 'Dlamini', 'buhle.dlamini@gmail.com', 'Dobsonville'),
    ('Busisiwe', 'Mabena', 'busisiwe.mabena2@gmail.com', 'Dobsonville Ext 1'),
    ('Dineo', 'Khumalo', 'dineo.khumalo@gmail.com', 'Dobsonville Ext 2'),
    ('Dumisani', 'Zulu', 'dumisani.zulu@gmail.com', 'Dobsonville'),
    ('Fikile', 'Ngcobo', 'fikile.ngcobo2@gmail.com', 'Dobsonville Ext 1'),
    ('Gugu', 'Mthembu', 'gugu.mthembu@gmail.com', 'Dobsonville Ext 2'),
    ('Hlengiwe', 'Mkhize', 'hlengiwe.mkhize2@gmail.com', 'Dobsonville'),
    ('Jabulani', 'Mabaso', 'jabulani.mabaso3@gmail.com', 'Dobsonville Ext 1'),
    ('Kagiso', 'Ntuli', 'kagiso.ntuli@gmail.com', 'Dobsonville Ext 2'),
    ('Khaya', 'Mhlongo', 'khaya.mhlongo@gmail.com', 'Dobsonville'),
    ('Khanyisa', 'Zungu', 'khanyisa.zungu@gmail.com', 'Dobsonville Ext 1'),
    ('Lindiwe', 'Majozi', 'lindiwe.majozi2@gmail.com', 'Dobsonville Ext 2'),
    ('Lulama', 'Ngwenya', 'lulama.ngwenya@gmail.com', 'Dobsonville'),
    ('Lungile', 'Mthethwa', 'lungile.mthethwa3@gmail.com', 'Dobsonville Ext 1'),
    ('Luyolo', 'Mkhize', 'luyolo.mkhize@gmail.com', 'Dobsonville'),
    ('Mangaliso', 'Mabaso', 'mangaliso.mabaso2@gmail.com', 'Dobsonville Ext 1'),
    ('Mbalenhle', 'Ntuli', 'mbalenhle.ntuli@gmail.com', 'Dobsonville Ext 2'),
    ('Mduduzi', 'Mhlongo', 'mduduzi.mhlongo3@gmail.com', 'Dobsonville'),
    ('Melokuhle', 'Zungu', 'melokuhle.zungu@gmail.com', 'Dobsonville Ext 1'),
    ('Menzi', 'Majozi', 'menzi.majozi@gmail.com', 'Dobsonville Ext 2'),
    ('Mpho', 'Ngwenya', 'mpho.ngwenya2@gmail.com', 'Dobsonville'),
    ('Nandipha', 'Mthembu', 'nandipha.mthembu2@gmail.com', 'Dobsonville Ext 1'),
    ('Nhlakanipho', 'Mkhize', 'nhlakanipho.mkhize2@gmail.com', 'Dobsonville Ext 2'),
    ('Nkosinathi', 'Mabaso', 'nkosinathi.mabaso2@gmail.com', 'Dobsonville'),
    ('Nokubonga', 'Ntuli', 'nokubonga.ntuli2@gmail.com', 'Dobsonville Ext 1'),
    ('Nomathamsanqa', 'Mhlongo', 'nomathamsanqa.mhlongo@gmail.com', 'Dobsonville Ext 2'),
    ('Nomonde', 'Zungu', 'nomonde.zungu3@gmail.com', 'Dobsonville'),
    ('Nompumelelo', 'Majozi', 'nompumelelo.majozi@gmail.com', 'Dobsonville Ext 1'),
    ('Nonhlanhla', 'Ngwenya', 'nonhlanhla.ngwenya@gmail.com', 'Dobsonville Ext 2'),
    ('Nosihle', 'Mthethwa', 'nosihle.mthethwa3@gmail.com', 'Dobsonville'),
    ('Ntando', 'Dlamini', 'ntando.dlamini@gmail.com', 'Dobsonville Ext 1'),
    ('Ntombizodwa', 'Mabena', 'ntombizodwa.mabena@gmail.com', 'Dobsonville Ext 2'),
    ('Ntombezinhle', 'Khumalo', 'ntombezinhle.khumalo@gmail.com', 'Dobsonville'),
    ('Nwabisa', 'Zulu', 'nwabisa.zulu3@gmail.com', 'Dobsonville Ext 1'),
    ('Phakamani', 'Ngcobo', 'phakamani.ngcobo@gmail.com', 'Dobsonville Ext 2'),
    ('Phindile', 'Mthembu', 'phindile.mthembu3@gmail.com', 'Dobsonville'),
    ('Sanele', 'Mkhize', 'sanele.mkhize@gmail.com', 'Dobsonville Ext 1'),
    ('Sbusiso', 'Mabaso', 'sbusiso.mabaso2@gmail.com', 'Dobsonville Ext 2'),
    ('Sibongile', 'Ntuli', 'sibongile.ntuli@gmail.com', 'Dobsonville'),
    ('Simphiwe', 'Mhlongo', 'simphiwe.mhlongo2@gmail.com', 'Dobsonville Ext 1'),
    ('Siphesihle', 'Zungu', 'siphesihle.zungu4@gmail.com', 'Dobsonville Ext 2'),
    ('Siyanda', 'Majozi', 'siyanda.majozi@gmail.com', 'Dobsonville'),
    ('Siyavuya', 'Ngwenya', 'siyavuya.ngwenya3@gmail.com', 'Dobsonville Ext 1'),
    ('Sizwe', 'Mthethwa', 'sizwe.mthethwa3@gmail.com', 'Dobsonville Ext 2'),
    ('Thabang', 'Dlamini', 'thabang.dlamini@gmail.com', 'Dobsonville'),
    ('Thandeka', 'Mabena', 'thandeka.mabena@gmail.com', 'Dobsonville Ext 1'),
    ('Thando', 'Khumalo', 'thando.khumalo@gmail.com', 'Dobsonville Ext 2'),
    ('Themba', 'Zulu', 'themba.zulu@gmail.com', 'Dobsonville'),
    ('Thobeka', 'Ngcobo', 'thobeka.ngcobo2@gmail.com', 'Dobsonville Ext 1'),
    ('Thulani', 'Mthembu', 'thulani.mthembu4@gmail.com', 'Dobsonville Ext 2'),
    ('Vuyani', 'Mkhize', 'vuyani.mkhize3@gmail.com', 'Dobsonville'),
    ('Vuyelwa', 'Mabaso', 'vuyelwa.mabaso2@gmail.com', 'Dobsonville Ext 1'),
    ('Xolani', 'Ntuli', 'xolani.ntuli@gmail.com', 'Dobsonville Ext 2'),
    ('Yandiswa', 'Mhlongo', 'yandiswa.mhlongo@gmail.com', 'Dobsonville'),
    ('Yonela', 'Zungu', 'yonela.zungu2@gmail.com', 'Dobsonville Ext 1'),
    ('Zanele', 'Majozi', 'zanele.majozi3@gmail.com', 'Dobsonville Ext 2'),
    ('Zandile', 'Ngwenya', 'zandile.ngwenya@gmail.com', 'Dobsonville'),
    ('Zikhona', 'Mthethwa', 'zikhona.mthethwa@gmail.com', 'Dobsonville Ext 1'),
    ('Zimasa', 'Dlamini', 'zimasa.dlamini@gmail.com', 'Dobsonville Ext 2'),
    ('Zinhle', 'Mabena', 'zinhle.mabena@gmail.com', 'Dobsonville'),
    ('Zola', 'Khumalo', 'zola.khumalo@gmail.com', 'Dobsonville Ext 1'),
    ('Zukiswa', 'Zulu', 'zukiswa.zulu3@gmail.com', 'Dobsonville Ext 2'),
    ('Zandile', 'Mabaso', 'zandile.mabaso3@gmail.com', 'Dobsonville'),
    ('Zikhona', 'Ntuli', 'zikhona.ntuli@gmail.com', 'Dobsonville Ext 1'),
    ('Zimasa', 'Mhlongo', 'zimasa.mhlongo@gmail.com', 'Dobsonville Ext 2'),
    ('Zinhle', 'Zungu', 'zinhle.zungu3@gmail.com', 'Dobsonville'),
    ('Zola', 'Majozi', 'zola.majozi@gmail.com', 'Dobsonville Ext 1'),
    ('Zukiswa', 'Ngwenya', 'zukiswa.ngwenya3@gmail.com', 'Dobsonville Ext 2'),
    ('Akhona', 'Mthethwa', 'akhona.mthethwa3@gmail.com', 'Dobsonville'),
    ('Andiswa', 'Dlamini', 'andiswa.dlamini@gmail.com', 'Dobsonville Ext 1'),
    ('Anele', 'Mabena', 'anele.mabena2@gmail.com', 'Dobsonville Ext 2'),
    ('Asanda', 'Khumalo', 'asanda.khumalo@gmail.com', 'Dobsonville'),
    ('Ayanda', 'Zulu', 'ayanda.zulu3@gmail.com', 'Dobsonville Ext 1'),
    ('Babalwa', 'Ngcobo', 'babalwa.ngcobo@gmail.com', 'Dobsonville Ext 2'),
    ('Bandile', 'Mthembu', 'bandile.mthembu2@gmail.com', 'Dobsonville'),
    ('Bhekisisa', 'Mkhize', 'bhekisisa.mkhize3@gmail.com', 'Dobsonville Ext 1'),
    ('Bongiwe', 'Mabaso', 'bongiwe.mabaso@gmail.com', 'Dobsonville Ext 2'),
    ('Buhle', 'Ntuli', 'buhle.ntuli@gmail.com', 'Dobsonville'),
    ('Busisiwe', 'Mhlongo', 'busisiwe.mhlongo@gmail.com', 'Dobsonville Ext 1'),
    ('Dineo', 'Zungu', 'dineo.zungu@gmail.com', 'Dobsonville Ext 2'),
    ('Dumisani', 'Majozi', 'dumisani.majozi@gmail.com', 'Dobsonville'),
    ('Fikile', 'Ngwenya', 'fikile.ngwenya3@gmail.com', 'Dobsonville Ext 1'),
    ('Gugu', 'Mthethwa', 'gugu.mthethwa2@gmail.com', 'Dobsonville Ext 2'),
    ('Hlengiwe', 'Dlamini', 'hlengiwe.dlamini@gmail.com', 'Dobsonville'),
    ('Jabulani', 'Mabena', 'jabulani.mabena4@gmail.com', 'Dobsonville Ext 1'),
    ('Kagiso', 'Khumalo', 'kagiso.khumalo@gmail.com', 'Dobsonville Ext 2'),
    ('Khaya', 'Zulu', 'khaya.zulu2@gmail.com', 'Dobsonville'),
    ('Khanyisa', 'Ngcobo', 'khanyisa.ngcobo2@gmail.com', 'Dobsonville Ext 1'),
    ('Lindiwe', 'Mthembu', 'lindiwe.mthembu3@gmail.com', 'Dobsonville Ext 2'),
    ('Lulama', 'Mkhize', 'lulama.mkhize3@gmail.com', 'Dobsonville'),
    ('Lungile', 'Mabaso', 'lungile.mabaso@gmail.com', 'Dobsonville Ext 1'),
    ('Luyolo', 'Ntuli', 'luyolo.ntuli@gmail.com', 'Dobsonville Ext 2'),
    ('Mangaliso', 'Mhlongo', 'mangaliso.mhlongo3@gmail.com', 'Dobsonville'),
    ('Akhona', 'Ngcobo', 'akhona.ngcobo2@gmail.com', 'Dobsonville'),
    ('Andiswa', 'Mthembu', 'andiswa.mthembu3@gmail.com', 'Dobsonville Ext 1')
    ) AS names(first_name, last_name, email, township)
)
INSERT INTO users (
    id, first_name, last_name, full_name, email, phone, role_id, status,
    street_addr, subdivision, city, postal_code, created_at, updated_at
)
SELECT
    gen_random_uuid(),
    first_name,
    last_name,
    first_name || ' ' || last_name,
    email,
    NULL,
    (SELECT id FROM roles WHERE name = 'resident' LIMIT 1),
    'active',
    'Generated Address ' || (ROW_NUMBER() OVER () - 1)::TEXT,
    township,
    'Soweto',
    '1863',
    NOW(),
    NOW()
FROM numbered_names
ON CONFLICT (email) DO NOTHING;

-- Step 3: Verify the insert
SELECT
    COUNT(*) as total_users_created,
    COUNT(DISTINCT email) as unique_emails,
    COUNT(DISTINCT phone) as unique_phones
FROM users
WHERE email LIKE '%@gmail.com'
  AND created_at >= CURRENT_DATE;

-- Show sample of created users
SELECT
    first_name,
    last_name,
    email,
    phone,
    subdivision
FROM users
WHERE email LIKE '%@gmail.com'
  AND created_at >= CURRENT_DATE
ORDER BY created_at DESC
LIMIT 10;